// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/filetug/previewer_app.go
//
// Generated by this command:
//
//	mockgen -source=pkg/filetug/previewer_app.go -destination=pkg/filetug/previewer_app_mock.go -package=filetug
//

// Package filetug is a generated GoMock package.
package filetug

import (
	reflect "reflect"

	tview "github.com/rivo/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockPreviewerApp is a mock of PreviewerApp interface.
type MockPreviewerApp struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewerAppMockRecorder
	isgomock struct{}
}

// MockPreviewerAppMockRecorder is the mock recorder for MockPreviewerApp.
type MockPreviewerAppMockRecorder struct {
	mock *MockPreviewerApp
}

// NewMockPreviewerApp creates a new mock instance.
func NewMockPreviewerApp(ctrl *gomock.Controller) *MockPreviewerApp {
	mock := &MockPreviewerApp{ctrl: ctrl}
	mock.recorder = &MockPreviewerAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviewerApp) EXPECT() *MockPreviewerAppMockRecorder {
	return m.recorder
}

// QueueUpdateDraw mocks base method.
func (m *MockPreviewerApp) QueueUpdateDraw(f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueUpdateDraw", f)
}

// QueueUpdateDraw indicates an expected call of QueueUpdateDraw.
func (mr *MockPreviewerAppMockRecorder) QueueUpdateDraw(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueUpdateDraw", reflect.TypeOf((*MockPreviewerApp)(nil).QueueUpdateDraw), f)
}

// SetFocus mocks base method.
func (m *MockPreviewerApp) SetFocus(p tview.Primitive) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFocus", p)
}

// SetFocus indicates an expected call of SetFocus.
func (mr *MockPreviewerAppMockRecorder) SetFocus(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocus", reflect.TypeOf((*MockPreviewerApp)(nil).SetFocus), p)
}
