// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/files/store.go
//
// Generated by this command:
//
//	mockgen -source=pkg/files/store.go -destination=pkg/files/store_mock.go -package=files
//

// Package files is a generated GoMock package.
package files

import (
	context "context"
	url "net/url"
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CreateDir mocks base method.
func (m *MockStore) CreateDir(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDir", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDir indicates an expected call of CreateDir.
func (mr *MockStoreMockRecorder) CreateDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDir", reflect.TypeOf((*MockStore)(nil).CreateDir), ctx, path)
}

// CreateFile mocks base method.
func (m *MockStore) CreateFile(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateFile", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateFile indicates an expected call of CreateFile.
func (mr *MockStoreMockRecorder) CreateFile(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateFile", reflect.TypeOf((*MockStore)(nil).CreateFile), ctx, path)
}

// Delete mocks base method.
func (m *MockStore) Delete(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStoreMockRecorder) Delete(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStore)(nil).Delete), ctx, path)
}

// GetDirReader mocks base method.
func (m *MockStore) GetDirReader(ctx context.Context, path string) (DirReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDirReader", ctx, path)
	ret0, _ := ret[0].(DirReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDirReader indicates an expected call of GetDirReader.
func (mr *MockStoreMockRecorder) GetDirReader(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDirReader", reflect.TypeOf((*MockStore)(nil).GetDirReader), ctx, path)
}

// ReadDir mocks base method.
func (m *MockStore) ReadDir(ctx context.Context, path string) ([]os.DirEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadDir", ctx, path)
	ret0, _ := ret[0].([]os.DirEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadDir indicates an expected call of ReadDir.
func (mr *MockStoreMockRecorder) ReadDir(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadDir", reflect.TypeOf((*MockStore)(nil).ReadDir), ctx, path)
}

// RootTitle mocks base method.
func (m *MockStore) RootTitle() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootTitle")
	ret0, _ := ret[0].(string)
	return ret0
}

// RootTitle indicates an expected call of RootTitle.
func (mr *MockStoreMockRecorder) RootTitle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootTitle", reflect.TypeOf((*MockStore)(nil).RootTitle))
}

// RootURL mocks base method.
func (m *MockStore) RootURL() url.URL {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RootURL")
	ret0, _ := ret[0].(url.URL)
	return ret0
}

// RootURL indicates an expected call of RootURL.
func (mr *MockStoreMockRecorder) RootURL() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RootURL", reflect.TypeOf((*MockStore)(nil).RootURL))
}

// MockDirReader is a mock of DirReader interface.
type MockDirReader struct {
	ctrl     *gomock.Controller
	recorder *MockDirReaderMockRecorder
	isgomock struct{}
}

// MockDirReaderMockRecorder is the mock recorder for MockDirReader.
type MockDirReaderMockRecorder struct {
	mock *MockDirReader
}

// NewMockDirReader creates a new mock instance.
func NewMockDirReader(ctrl *gomock.Controller) *MockDirReader {
	mock := &MockDirReader{ctrl: ctrl}
	mock.recorder = &MockDirReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirReader) EXPECT() *MockDirReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockDirReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockDirReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockDirReader)(nil).Close))
}

// Readdir mocks base method.
func (m *MockDirReader) Readdir() ([]os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Readdir")
	ret0, _ := ret[0].([]os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Readdir indicates an expected call of Readdir.
func (mr *MockDirReaderMockRecorder) Readdir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Readdir", reflect.TypeOf((*MockDirReader)(nil).Readdir))
}
